version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
  Chrome:
    image: selenium/node-chromium:latest
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
  Firefox:
    image: selenium/node-firefox:latest
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
  FlightReservation :
    image: poorna89/poornadocker
    depends_on:
      - Chrome
      - Firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=FlightReservation.xml
    volumes:
      - ./output:/home/selenium-docker/test-output
