version: "3"
services:
  FlightReservation :
    image: poorna89/poornadocker
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=FlightReservation.xml
    volumes:
      - ./output:/home/selenium-docker/test-output
